
application: your-app-id-here
version: your-version-here
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

libraries:
- name: ssl
  version: latest

builtins:
- deferred: on
